# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-02 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200629_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newswebsite',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
