# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-09 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200704_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
