# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-09 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_news_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='favourite',
        ),
        migrations.AddField(
            model_name='news',
            name='watch_later',
            field=models.ManyToManyField(blank=True, related_name='watch_later', to=settings.AUTH_USER_MODEL),
        ),
    ]
